@startuml

title Diagramme Séquence de la gestion d'une Publicité

actor Agent as A


A -> vueAllPublicites 
A //-- vueAllPublicites :afficher liste Publicites

alt Créer Publicité
vueAllPublicites -> vuePublicites :nouvellePublicites()


A //-- vuePublicites :afficher Publicité vide

A -> vuePublicites : saisie Information(s)
A -> vuePublicites : valide

vuePublicites -> ControleurPublicites : verifPublicite()

ControleurPublicites -> ControleurPublicites : p = new Publicites(info)
ControleurPublicites -> MyAgencyManager : listePubs.add(p)

MyAgencyManager -> vueAllPublicites : actualiserListe()

A //-- vueAllPublicites : afficher nouvelle liste


else Afficher Publicité
vueAllPublicites -> vuePublicites : afficherPublicites(p)
A //-- vuePublicites :afficher p

else Modifier Publicité

vueAllPublicites -> vuePublicites : modifierPublicites(p)
A //-- vuePublicites :afficher p

A -> vuePublicites : saisie Information(s)
A -> vuePublicites : valide

vuePublicites -> ControleurPublicites : verifPub()

ControleurPublicites -> MyAgencyManager : listePubs.get(p)
MyAgencyManager -> ControleurPublicites : p

loop attribute a in p
ControleurPublicites -> ControleurPublicites :p.setA(info.a)
end

ControleurPublicites -> vuePublicites : afficherPublicites()
A //-- vuePublicites :afficher p

else Supprimer Publicité
vueAllPublicites -> ControleurPublicites : supprimerPublicites(p)
A //-- ControleurPublicites : Supprimer ?
alt oui
ControleurPublicites -> MyAgencyManager : listePublicites.remove(p)
MyAgencyManager -> vueAllPublicites : actualiserListe()

end
A //-- vueAllPublicites : afficher nouvelle liste
end
@enduml