@startuml

title Diagramme d'activité de l'enregistrement d'une vente\n

start

:Prendre RdvRecherche avec Acheteur;

:Proposer Biens;

repeat
  :Prendre RdvVisite avec Client;
repeat while (Client satisfait Bien ?)

:Prendre RdvPromesseVente avec Acheteur et Vendeur;

if (Acheteur se rétracte avant date de vente) then (yes)
  :Vendeur reste propriétaire;
else (no)
  :Acheteur devient propriétaire;
endif

stop

@enduml