@startuml

title Diagramme Séquence de la création d'un Rdv

actor User as U
U -> MyAgencyManager :CréerRdv()

MyAgencyManager -> Rdv :new Rdv() c

MyAgencyManager -> vueRdv : vueRdv(c)

U //-- vueRdv :afficher Rdv

U -> vueRdv :Saisit Information(s)
U -> vueRdv :Valide saisie

vueRdv -> ControleurRdv :Verifie Information(s)
ControleurRdv -> Rdv :Modifie Information(s)
@enduml
