@startuml

title Diagramme Séquence de la Modification d'un bien

actor User as U
U -> MyAgencyManager :getListeBiens()


MyAgencyManager -> vueBien : vueBien(c)

U //-- vueBien :afficher Bien

U -> vueBien :Saisit Information(s)
U -> vueBien :Valide saisie

vueBien -> ControleurBien :Verifie Information(s)
ControleurBien -> Bien :Modifie Information(s)

vueBien //-- Bien :renvoie les modifs
U //-- vueBien :afficheBien
@enduml
