@startuml

title Diagramme des Classes

package Modele <<Folder>> {

    package modeleAgence<<Frame>> {
        class MyAgencyManager {
        -ArrayList<Client>
        -ArrayList<Mandat>
        -ArrayList<Publicites>
        -ArrayList<RDV>
        }
        
    class Mandat{
        -Bien maison
        -Client vendeur
        -Date butoir
        -Client acheteur = null
        -boolean sommeTotalVerse
    }
     MyAgencyManager"1" <- "*" Mandat
    }
    package modeleClient <<Frame>> {
        abstract Client {
        -String nom
          -String adresse
          -String numTel
          -String mail
          +void Client(String nom,String adresse,String numTel,String mail)

        }
        class ClientPhysique extends Client{
        }
    
        class ClientMoral extends Client{
            -String formeJuridique
            -String nSIREN
            +void ClientMoral(String juridic, String siren)
        }
    }

    package modeleBien <<Frame>> {
        enum Orientation{
            NORD
            SUD
            EST
            OUEST
         }
        abstract Bien {
            -int id
            -String adresse
            -Orientation orient
            +void Bien(String adresse, Orientation orient) 
        }
        class Terrain extends Bien{
        -double surfaceTotal
            -double longueurFacade
            +void Terrain(String adresse, Orientation orient,double surfaceTotal, double lgrFacade)
        }
        class Maison extends Bien{
            -Terrain terrain
            -double surfaceHabitable
            -int nbPiece
            -int nbEtage
            -String moyenChauff
            +void Maison(String adresse, Orientation orient,double surfaceHabit, int piece, int etage, String chauff,Terrain terrain)
        }
        class Appartement extends Bien{
        -int nbPiece
            -int etage
            -double chargesMensuelles
            +void Appartement(String adresse, Orientation orient,int piece, int etage, double charges)
        }
        Terrain  o-- "0.*" Maison
    }

    package modeleRDV <<Frame>> {
        abstract RDV{
        }

        class RdvMandat extends RDV{
        }

        class RdvPromesseVente extends RDV{
        }

        class RdvRecherche extends RDV{
        }

    }

    package modeleAutres <<Frame>> {
	
		enum TypePub{
		}
        class Publicites{
        }
		
    }
    
    MyAgencyManager "1" <-- "*" Client
    MyAgencyManager "1" <-- "*" RDV
    MyAgencyManager "1" <-- "*" Publicites

    
    Mandat o- Client
    Mandat o- Bien
    
	Bien <-- Orientation
	Publicites <-- TypePub
}


package Vue <<Folder>> {
}

package Controleur <<Folder>> {
}

Vue -> Modele : READ
Vue -> Controleur : WRITE
Controleur -> Modele : MODIFY


@enduml
