@startuml

title Diagramme Séquence de la création  d'un Dossier

actor User as U
U -> MyAgencyManager :CréerDossier()

MyAgencyManager -> Dossier :new Dossier() d
MyAgencyManager -> vueDossier : vueDossier(d)

vueDossier -> MyAgencyManager : getClients()
vueDossier -> MyAgencyManager : getBiens()

U -> vueDossier :Saisit Information(s)
U -> vueDossier :Choisir Client
U -> vueDossier :Choisir Bien

U -> vueDossier :Valide saisie

vueDossier -> ControleurDossier :Verifie Information(s)

ControleurDossier -> Dossier :Modifie Information(s)
@enduml
