@startuml

title Diagramme Séquence de la création  d'un Dossier

actor User as U
U -> MyAgencyManager :CréerDossier()

MyAgencyManager -> Dossier :new Dossier() d
MyAgencyManager -> vueDossier : vueDossier(d)

U -> vueDossier :Saisit Information(s)
U -> vueDossier :Saisit Bien(b)
U -> vueDossier :ChangerEtat()


U -> vueDossier :Valide saisie

vueDossier -> ControleurDossier :Verifie Information(s)
vueDossier -> ControleurBien :Verifie Information(b)
ControleurBien -> Dossier :ModifieBien(b)


ControleurDossier -> Dossier :Modifie Information(s)
@enduml
