@startuml

title Diagramme Séquence de la création d'un Bien

actor User as U
U -> MyAgencyManager :CréerBien()

MyAgencyManager -> Bien :new Bien() b

MyAgencyManager -> vueBien : vueBien(b)

vueBien -> MyAgencyManager : getClients()
U -> vueBien :Choisir Propriétaire
U -> vueBien :Saisit Information(s)
U -> vueBien :Valide saisie

vueBien -> ControleurBien :Verifie Information(s)
ControleurBien -> Bien :Modifie Information(s)
@enduml