@startuml

title Diagramme Séquence de la gestion d'un RDV

actor Agent as A


A -> vueAllRdvs 
A //-- vueAllRdvs :afficher liste RDV

alt Créer RDV
vueAllRdvs -> vueRDVs :nouveauRDV()


A //-- vueRDVs :afficher RDV vide

A -> vueRDVs : saisie Information(s)
A -> vueRDVs : valide

vueRDVs -> ControleurRDV : verifRDV()

ControleurRDV -> ControleurRDV : p = new RDV(info)
ControleurRDV -> MyAgencyManager : listeRDV.add(p)

MyAgencyManager -> vueAllRdvs : actualiserListe()

A //-- vueAllRdvs : afficher nouvelle liste


else Afficher RDV
vueAllRdvs -> vueRDVs : afficherRDVs(p)
A //-- vueRDVs :afficher p

else Modifier RDV

vueAllRdvs -> vueRDVs : modifierRDVs(p)
A //-- vueRDVs :afficher p

A -> vueRDVs : saisie Information(s)
A -> vueRDVs : valide

vueRDVs -> ControleurRDV : verifPub()

ControleurRDV -> MyAgencyManager : listeRDV.get(p)
MyAgencyManager -> ControleurRDV : p

loop attribute a in p
ControleurRDV -> ControleurRDV :p.setA(info.a)
end

ControleurRDV -> vueRDVs : afficherRDVs()
A //-- vueRDVs :afficher p
else Supprimer RDV
vueAllRdvs -> ControleurRDV : supprimerRDVs(p)
A //-- ControleurRDV : Supprimer ?
alt oui
ControleurRDV -> MyAgencyManager : listeRDV.remove(p)
MyAgencyManager -> vueAllRdvs : actualiserListe()

end
A //-- vueAllRdvs : afficher nouvelle liste
end
@enduml