@startuml

title Diagramme des cas d'utilisations

:Personne: as P
:Entreprise: as E
:Agence: as A

(Vendre Maison) as Vendre
(Acheter Maison) as Acheter
(S'incrire dans l'agence) As Inscript
(Rdv Mandat de Vente) as RDVm
(Se renseigner sur Maison) as getInfoMaison
(Faire sa publicité) as pub
(Faire ses statistiques) as stats
(Rdv Promesse de vente) as RDVp
(Verser Promesse de Vente) as givePromesse
(Se rétracter) as retract
(Verser reste Prix de vente) as giveFull
(Proposer Visite) as RDVv

E -up-|> P

P --> Vendre
P --> Acheter
P -> Inscript
P --> RDVm
A --> getInfoMaison
A --> pub
A --> stats
P --> RDVp : Vendeur
P --> RDVp : Acheteur
P --> givePromesse
givePromesse ..> retract :<<include>>
P --> giveFull
A --> RDVv

@enduml