@startuml

title Diagramme des cas d'utilisations

:Users: as U

rectangle MyAgencyManager{
  (Créer Client) as CC
  (Créer Bien) as CB
  (Créer RDV) as CR
  (Créer Dossier Vente) as CD
  (Créer Publicitée) as CP
  (Créer Mandat) as CM
  (Effectuer Vente) as CV
(Afficher Statistiques) as AS

  (Voir Bien) as VB
  (Voir Client) as VC
  (Voir RDV) as VR
  (Modifier Bien) as MB
  (Modifier Client) as MC
  (Modifier RDV) as MR
}

left to right direction
U -->CC
U -->CB
U -->CD
U -->CP

CD <.. CM : <<extend>>
CD <.. CV : <<extend>>
CM <.. CR : <<include>>
CV <.. CR : <<include>>


U --> VC
VC <.. MC : <<extend>>
VC <.. VR : <<extend>>
VR <.. MR : <<extend>>
U --> VB
VB <.. MB : <<extend>>
U -->AS


@enduml
